[build]
target = "tools/i386-unknown-nanvix.json"
rustflags = ["-C", "target-feature=-crt-static"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
