[build]
target = "tools/i386-unknown-nanvix.json"
rustflags = [
    "-C", "link-arg=-T./lib/link.ld",
    "-C", "link-arg=--sysroot=./",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
